server:
  port: 2006
  context-path: /

eureka:
  instance:
    #hostname: localhost #eureka注册中心实例名称 单机的时候
    hostname: eureka2006.java1234.com # 集群
  client:
    register-with-eureka: false     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到，单机的时候
      defaultZone: http://eureka2004.java1234.com:2004/eureka/,http://eureka2002.java1234.com:2002/eureka/ # 集群